config/routes.rb
require "sidekiq/web"

Wukumurl::Application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations',
    confirmations: 'confirmations',
    passwords: 'passwords'
  }

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end
  mount Sidekiq::Web, at: "/sidekiq"


  devise_scope :user do
    get "login", to: "devise/sessions#new"
    post "login", to: "devise/sessions#create"

    get "logout", to: "devise/sessions#destroy"

    get "register", to: "devise/registrations#new"
    post "register", to: "devise/registrations#create"

    get "forgot_password", to: "devise/passwords#new"
    post "forgot_password", to: "devise/passwords#create"
  end

  match '/' => 'short_urls#create', :controller => 'short_urls', :via => :post

  namespace :admin do
    resources :dashboard, :only => [:index]
  end

  get "/short_urls/list",
    :controller => 'short_urls',
    :action => :list
  resources :short_urls

  get "/:short_name/organizations_table", to: "short_urls#organizations_table"
  get "/:short_name", :controller => 'short_urls', :action => :visit,
    :as => 'visit_short_url'
  get "/:short_name/info",
    :controller => 'short_urls',
    :action => :show,
    :as => 'short_url_info'

  resources :organizations, only: [:destroy]
  resources :users, only: [:update]
  resources :teams, only: [:show]

  authenticate :user do
    get '/wcmc_overview', to: 'short_urls#index', as: 'wcmc_overview_path'
    get '/users/my_links', to: 'users#show', as: 'user_links'
    get '/users/pick_team', to: 'users#pick_team', as: 'pick_team'
  end

  authenticated :user do
    root to: 'short_urls#index', as: :authenticated_root
    #root to: redirect('/users/my_links'), as: :authenticated_root
  end

  root to: 'static_pages#index', as: :root
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_filter :authenticate_admin
  before_filter :dont_show_map

  def index
    @short_urls = ShortUrl.all
  end
end

app/views/admin/dashboard/index.html.erb
<table class="dataTable" id="dataTable">
  <% @short_urls.each do |short_url| %>
    <thead>
      <tr>
        <th>Short Name</th>
        <th>URL</th>
        <th>Owner</th>
        <th>Deleted?</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= short_url.short_name %></td>
        <td><%= short_url.url %></td>
        <td><%= short_url.user.email %></td>
        <td><%= short_url.deleted ? 'Yes' : 'No' %></td>
        <td><%= link_to 'Edit', edit_short_url_path(short_url) %></td>
        <td><%= link_to 'Delete', short_url_path(short_url), method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    </tbody>
  <% end %>
</table>