config/routes.rb
require "sidekiq/web"

Wukumurl::Application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations',
    confirmations: 'confirmations',
    passwords: 'passwords'
  }

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end
  mount Sidekiq::Web, at: "/sidekiq"


  devise_scope :user do
    get "login", to: "devise/sessions#new"
    post "login", to: "devise/sessions#create"

    get "logout", to: "devise/sessions#destroy"

    get "register", to: "devise/registrations#new"
    post "register", to: "devise/registrations#create"

    get "forgot_password", to: "devise/passwords#new"
    post "forgot_password", to: "devise/passwords#create"
  end

  match '/' => 'short_urls#create', :controller => 'short_urls', :via => :post

  namespace :admin do
    resources :dashboard, :only => [:index]
  end

  get "/short_urls/list",
    :controller => 'short_urls',
    :action => :list
  resources :short_urls

  get "/:short_name/organizations_table", to: "short_urls#organizations_table"
  get "/:short_name", :controller => 'short_urls', :action => :visit,
    :as => 'visit_short_url'
  get "/:short_name/info",
    :controller => 'short_urls',
    :action => :show,
    :as => 'short_url_info'

  resources :organizations, only: [:destroy]
  resources :users, only: [:update]
  resources :teams, only: [:show]

  authenticate :user do
    get '/wcmc_overview', to: 'short_urls#index', as: 'wcmc_overview_path'
    get '/users/my_links', to: 'users#show', as: 'user_links'
    get '/users/pick_team', to: 'users#pick_team', as: 'pick_team'
  end

  authenticated :user do
    root to: 'short_urls#index', as: :authenticated_root
    #root to: redirect('/users/my_links'), as: :authenticated_root
  end

  root to: 'static_pages#index', as: :root
end

app/views/shared/_create_short_link_modal.html.erb
<div id="create-link-modal" class="modal" title="Share a link" style="display:none;">
<%= form_for ShortUrl.new, url: { controller: "short_urls", action: "create" } do |f| %>
  <%= f.label :url, "Paste your link" %>
  <%= f.text_field :url %>

  <div class="divider"><span>Or</span></div>

  <%= f.label "Select a file from your Dropbox" %>
  <%= link_to "#", class: "btn btn-secondary stretch dropbox-button" do %>
    <%= fa_icon "dropbox" %> Choose from Dropbox
  <% end %>

  <div class="divider"><span>Or</span></div>

  <%= f.label "Select a file from your OneDrive" %>
  <%= link_to "#", class: "btn btn-secondary stretch onedrive-button", data: { 'ms-app-id': Rails.application.secrets.onedrive["app_id"] } do %>
    <%= fa_icon "cloud" %> Choose from OneDrive
  <% end %>

  <hr>

  <%= f.label :user_id, "Owner" %>
  <%= f.collection_select :user_id, current_user.team_mates, :id, :full_name, { prompt: "Select a user",  selected: current_user.id } %>

  <%= f.label :description, "Add a description" %>
  <% # Toggle Switch %>
  <%= f.text_area :description %>

  <%= f.label :short_name, "Edit the URL name before sharing" %>
  <%= f.text_field :short_name %>

  <%= f.label :private, "Make this link private" %>
  <%= f.check_box :private %>

  <br>

  <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_edit_short_link_modal.html.erb
<div id="edit-link-modal-<%= short_url.id %>" class="modal edit-link-modal" title="Edit this link" style="display:none;">
<%= form_for short_url, method: :put do |f| %>
  <%= f.label :url, "Paste your link" %>
  <%= f.text_field :url %>

  <div class="divider"><span>Or</span></div>

  <%= f.label "Select a file from your Dropbox" %>
  <%= link_to "#", class: "btn btn-secondary stretch dropbox-button" do %>
    <%= fa_icon "dropbox" %> Choose from Dropbox
  <% end %>

  <div class="divider"><span>Or</span></div>

  <%= f.label "Select a file from your OneDrive" %>
  <%= link_to "#", class: "btn btn-secondary stretch onedrive-button", data: { 'ms-app-id': Rails.application.secrets.onedrive["app_id"] } do %>
    <%= fa_icon "cloud" %> Choose from OneDrive
  <% end %>

  <hr>

  <%= f.label :user_id, "Owner" %>
  <%= f.collection_select :user_id, current_user.team_mates, :id, :full_name %>

  <%= f.label :description, "Add a description" %>
  <% # Toggle Switch %>
  <%= f.text_area :description %>

  <%= f.label :short_name, "Edit the URL name before sharing" %>
  <%= f.text_field :short_name %>

  <%= f.label :private, "Make this link private" %>
  <%= f.check_box :private %>

  <br>

  <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer>
</footer>

app/views/shared/_header.html.erb
<div class="header">
  <div class="container">
    <div class="left">
      <a href="https://unep-wcmc.org" target="_blank" class="unepwcmc-logo"></a>
    </div>
    <div class="triangle"></div>
    <div class="strapline">
      <%= image_tag 'wcmcio-logo.png', size: '30' %>
      <span>WCMC.io</span><div class="vertical-divider"></div>  Measure the impact of digital documents you care about
    </div>
    <div class="right">
      <% if current_user %>
        <div>
          <%= link_to edit_user_registration_path do %>
            <%= fa_icon 'user' %> Edit My Account
          <% end %>
        </div>
        <div class="vertical-divider"></div>
        <div>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <%= fa_icon 'sign-out' %> Log Out
          <% end %>
        </div>
      <% else %>
        <div>
          <%= link_to '#', class: "sign-up-link" do %>
            <%= fa_icon 'user' %> Sign Up
          <% end %>
        </div>
        <div class="vertical-divider"></div>
        <div>
          <%= link_to '#', class: "sign-in-link" do %>
            <%= fa_icon 'sign-in' %> Sign In
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? && current_user.team.present? %>
  <nav class="container">
    <div>
      <div>
        <%= nav_link_with_class 'WCMC', root_path %>
        <%= nav_link_with_class 'My Team', team_path(current_user.team.slug) %>
        <%= nav_link_with_class 'My Links', user_links_path %>
      </div>
      <%= link_to "#", id: "create-link", class: "btn btn-primary" do %>
        <%= fa_icon "share-alt" %> Share a link
      <% end %>
    </div>
  </nav>
<% end %>

app/views/shared/_short_link_history_modal.html.erb
<div id="change-history-modal-<%= short_url.id %>" class="modal history-modal" title="Change History" style="display:none;">
  <% if short_url.versions.blank? %>
    <p>This link has no change history yet</p>
  <% else %>
    <table class="table">
      <thead>
        <th>Change</th>
        <th>Author</th>
        <th>Date</th>
      </thead>
      <tbody>
        <% short_url.versions.last(10).each do |v| %>
          <tr>
            <td><%= v.event %></td>
            <td><%= v.whodunnit? ? v.whodunnit : "Admin" %></td>
            <td><%= v.created_at.strftime("%I:%M%p %d/%m/%Y") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/shared/_summary_stats.html.erb
<div class="row group">
  <div class="col col-3">
    <div class="page-header"><p class="headline">Number of Visits</p></div>
    <h2 class="text-primary"><%= number_with_delimiter(number_of_visits) %></h2>
  </div>
  <div class="col col-3">
    <div class="page-header"><p class="headline">Unique Visits</p></div>
    <h2 class="text-primary"><%= number_with_delimiter(unique_visits) %></h2>
  </div>
  <div class="col col-3">
    <div class="page-header"><p class="headline">Number of Links Shared</p></div>
    <h2 class="text-primary"><%= number_with_delimiter(number_of_links_shared) %></h2>
  </div>
  <div class="col col-3">
    <div class="page-header"><p class="headline">Countries Reached</p></div>
    <h2 class="text-primary"><%= number_with_delimiter(countries_reached) %></h2>
  </div>
</div>