config/routes.rb
require "sidekiq/web"

Wukumurl::Application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations',
    confirmations: 'confirmations',
    passwords: 'passwords'
  }

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end
  mount Sidekiq::Web, at: "/sidekiq"


  devise_scope :user do
    get "login", to: "devise/sessions#new"
    post "login", to: "devise/sessions#create"

    get "logout", to: "devise/sessions#destroy"

    get "register", to: "devise/registrations#new"
    post "register", to: "devise/registrations#create"

    get "forgot_password", to: "devise/passwords#new"
    post "forgot_password", to: "devise/passwords#create"
  end

  match '/' => 'short_urls#create', :controller => 'short_urls', :via => :post

  namespace :admin do
    resources :dashboard, :only => [:index]
  end

  get "/short_urls/list",
    :controller => 'short_urls',
    :action => :list
  resources :short_urls

  get "/:short_name/organizations_table", to: "short_urls#organizations_table"
  get "/:short_name", :controller => 'short_urls', :action => :visit,
    :as => 'visit_short_url'
  get "/:short_name/info",
    :controller => 'short_urls',
    :action => :show,
    :as => 'short_url_info'

  resources :organizations, only: [:destroy]
  resources :users, only: [:update]
  resources :teams, only: [:show]

  authenticate :user do
    get '/wcmc_overview', to: 'short_urls#index', as: 'wcmc_overview_path'
    get '/users/my_links', to: 'users#show', as: 'user_links'
    get '/users/pick_team', to: 'users#pick_team', as: 'pick_team'
  end

  authenticated :user do
    root to: 'short_urls#index', as: :authenticated_root
    #root to: redirect('/users/my_links'), as: :authenticated_root
  end

  root to: 'static_pages#index', as: :root
end

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47308714-1', 'unep.io');
  ga('send', 'pageview');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>wcmc.io shorten // share // track</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <script src="https://cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/3.15/cartodb.js"></script>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
    <div class="wrapper">
      <%= growlyflash_static_notices %>
      <%= render 'shared/header' %>
      <%= render 'shared/navbar' %>

      <div class="container content">
        <%= yield =%>
      </div>
      <% #= render 'shared/footer' %>


      <div id="sign-in-modal" class="modal" title="Sign In" style="display:none;">
        <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
          <div>
            <%= f.label :email %>
            <%= f.email_field :email, :autofocus => true %>
          </div>

          <div>
            <%= f.label :password %>
            <%= f.password_field :password %>
          </div>

          <hr>

          <div class="row group">
            <div class="col col-6">
              <% if devise_mapping.rememberable? %>
                <div>
                  <%= f.check_box :remember_me %>
                  <%= f.label :remember_me %>
                </div>
              <% end %>
            </div>

            <div class="col col-6">
              <%= f.submit "Sign in", class: 'btn btn-primary' %>
            </div>
          </div>
          <div class="row group">
            <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
              <%= link_to "Forgot password?", new_password_path(resource_name) %><br />
            <% end -%>
          </div>
        <% end %>

      </div>


      <div id="sign-up-modal" class="modal" title="Sign Up" style="display:none">
        <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>

          <div>
            <%= f.label :email %>
            <%= f.email_field :email, :autofocus => true %>
          </div>

          <div>
            <%= f.label :password %>
            <%= f.password_field :password %>
          </div>

          <div>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %>
          </div>

          <div class="row group">
            <div class="col col-6"><%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
              <%= link_to "Resend confirmation", new_confirmation_path(resource_name) %><br />
            <% end -%></div>
            <div class="col col-6"><%= f.submit "Sign up", class: 'btn btn-primary' %></div>
          </div>
        <% end %>
      </div>

    </div>


    <!-- Additional Scripts -->
    <% if Rails.env == 'production' %>
      <%= render "google_analytics" %>
    <% end %>
    <script type="text/javascript" src="https://js.live.net/v7.0/OneDrive.js"></script>
    <script type="text/javascript" src="https://www.dropbox.com/static/api/2/dropins.js" id="dropboxjs" data-app-key="<%= ENV["DROPBOX_API_KEY"] %>"></script>
  </body>
</html>